### ISSUE TITLE
Gracefully handle unauthenticated use of Censys.io Export API

### ISSUE THREAD

**Issue by Hwi-Kim** [18F/domain-scan#128]
Starting new HTTPS connection (1): www.censys.io
https://www.censys.io:443 "GET /api/v1/account HTTP/1.1" 200 243
Censys query:
SELECT parsed.subject.common_name, parsed.extensions.subject_alt_name.dns_names from FLATTEN([certificates.certificates], parsed.extensions.subject_alt_name.dns_names) where parsed.subject.common_name LIKE "%.gov" OR parsed.extensions.subject_alt_name.dns_names LIKE "%.gov";

Kicking off SQL query job.
https://www.censys.io:443 "POST /api/v1/export HTTP/1.1" 403 115
Traceback (most recent call last):

  File "/home/user/domain-scan/gatherers/censys.py", line 194, in export_mode
    job = export_api.new_job(query, format='csv', flatten=True)

  File "/home/user/domain-scan/censys/export.py", line 25, in new_job
    return self._post("export", data=data)

  File "/home/user/domain-scan/censys/base.py", line 111, in _post
    return self._make_call(self._session.post, endpoint, args, data)

  File "/home/user/domain-scan/censys/base.py", line 105, in _make_call
    const=const)

censys.base.CensysUnauthorizedException: 403 (unauthorized): Unauthorized. You do not have access to this service.

Censys error, aborting.
Downloading results of SQL query.
Traceback (most recent call last):
  File "./gather", line 175, in <module>
    run(options)
  File "./gather", line 73, in run
    for domain in gatherer.gather(suffix, options, extra):
  File "/home/user/domain-scan/gatherers/censys.py", line 66, in gather
    hostnames_map = export_mode(suffix, options, uid, api_key)
  File "/home/user/domain-scan/gatherers/censys.py", line 231, in export_mode
    utils.download(results_url, download_file)
  File "/home/user/domain-scan/scanners/utils.py", line 34, in download
    filename, headers = urllib.request.urlretrieve(url, destination)
  File "/usr/lib/python3.4/urllib/request.py", line 184, in urlretrieve
    url_type, path = splittype(url)
  File "/usr/lib/python3.4/urllib/parse.py", line 857, in splittype
    match = _typeprog.match(url)
TypeError: expected string or buffer

how can i run this

**Comment by konklone** [comment]
The relevant error is this one:

```
censys.base.CensysUnauthorizedException: 403 (unauthorized): Unauthorized. You do not have access to this service.
```

As documented in the README, "Use `--export` to use the [Censys.io Export API](https://censys.io/api/v1/docs/export), which is faster and more complete but requires researcher credentials."

We should handle this case more gracefully than a crash and a stack trace, but the issue is that you need to obtain Censys.io API credentials and set them to the right environment variables in order to use `--export` mode.

I'll leave this open until we implement a graceful handler with an informative error. Renaming the issue to describe that.
